# Generated by Django 6.0.2 on 2026-03-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_archived',
        ),
    ]
