# Generated by Django 6.0.2 on 2026-04-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('image_uploaded', 'Uploaded image'), ('image_deleted', 'Deleted image'), ('annotation_saved', 'Saved annotations'), ('annotation_done', 'Marked as done'), ('tag_added', 'Added tag'), ('tag_removed', 'Removed tag'), ('member_added', 'Added member'), ('member_removed', 'Removed member'), ('role_changed', 'Changed role'), ('project_created', 'Created project'), ('project_archived', 'Archived project'), ('project_restored', 'Restored project')], max_length=40)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
