# Generated by Django 6.0.2 on 2026-04-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_backfill_personal_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='planned_image_count',
            field=models.PositiveIntegerField(default=0, help_text='Expected total number of images for this project'),
        ),
    ]
