# Generated by Django 6.0.2 on 2026-04-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_workspace_planned_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_image_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
