# Generated by Django 6.0.2 on 2026-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_workspaceinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('image_uploaded', 'Uploaded image'), ('image_deleted', 'Deleted image'), ('annotation_saved', 'Saved annotations'), ('annotation_done', 'Marked as done'), ('tag_added', 'Added tag'), ('tag_removed', 'Removed tag'), ('member_added', 'Added member'), ('member_removed', 'Removed member'), ('role_changed', 'Changed role'), ('project_created', 'Created project'), ('project_archived', 'Archived project'), ('project_restored', 'Restored project'), ('export_yolo', 'Exported YOLO')], max_length=40),
        ),
    ]
