# Generated by Django 6.0.2 on 2026-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_emoji_remove_workspace_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotation_type',
            field=models.CharField(choices=[('bbox', 'Bounding Box'), ('polygon', 'Polygon'), ('segmentation', 'Segmentation'), ('classification', 'Classification'), ('mixed', 'Mixed')], default='bbox', max_length=20),
        ),
    ]
