# Generated by Django 6.0.2 on 2026-05-07 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_public_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('image_uploaded', 'Uploaded image'), ('image_deleted', 'Deleted image'), ('annotation_saved', 'Saved annotations'), ('annotation_done', 'Marked as done'), ('tag_added', 'Added tag'), ('tag_removed', 'Removed tag'), ('member_added', 'Added member'), ('member_removed', 'Removed member'), ('role_changed', 'Changed role'), ('project_created', 'Created project'), ('project_archived', 'Archived project'), ('project_restored', 'Restored project'), ('export_yolo', 'Exported YOLO'), ('export_csv', 'Exported CSV'), ('export_coco', 'Exported COCO'), ('export_json', 'Exported JSON')], max_length=40),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('member_added', 'Member added'), ('member_removed', 'Member removed'), ('role_changed', 'Role changed'), ('image_uploaded', 'Image uploaded'), ('image_deleted', 'Image deleted'), ('annotation_done', 'Annotation completed'), ('annotation_saved', 'Annotations saved'), ('tag_added', 'Tag added'), ('tag_removed', 'Tag removed'), ('project_created', 'Project created'), ('project_archived', 'Project archived'), ('project_restored', 'Project restored'), ('comment', 'New comment')], max_length=40)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='projects_no_recipie_1ca138_idx')],
            },
        ),
    ]
