# Generated by Django 6.0.2 on 2026-05-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_chatroom_chatmessage'),
        ('projects', '0016_task_taskcomment'),
    ]

    operations = [
    ]
