# Generated by Django 6.0.2 on 2026-03-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_tag_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending annotation'), ('partial', 'Partially annotated'), ('done', 'Annotated')], default='pending', max_length=20),
        ),
    ]
