# Generated by Django 6.0.2 on 2026-03-26 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Left edge as % of image width')),
                ('y', models.FloatField(help_text='Top edge as % of image height')),
                ('width', models.FloatField(help_text='Width as % of image width')),
                ('height', models.FloatField(help_text='Height as % of image height')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boxes', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounding_boxes', to='images.image')),
                ('label', models.ForeignKey(blank=True, help_text='Tag/label for this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounding_boxes', to='images.tag')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
