# Generated by Django 6.0.2 on 2026-04-17 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_boundingbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField(default=list, help_text='List of {x,y} percentage points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polygons', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='images.image')),
                ('label', models.ForeignKey(blank=True, help_text='Tag/label for this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polygons', to='images.tag')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
